services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
      DATABASE_URL: ${DATABASE_URL}
      CTVL_USERNAME: ${CTVL_USERNAME}
      CTVL_PASSWORD: ${CTVL_PASSWORD}
      CTVL_TOKEN_GROUP: ${CTVL_TOKEN_GROUP}
      CTVL_TOKEN_TEMPLATE: ${CTVL_TOKEN_TEMPLATE}
      CTVL_URL: ${CTVL_URL}
      NODE_TLS_REJECT_UNAUTHORIZED: ${NODE_TLS_REJECT_UNAUTHORIZED:-0}
      CTVL_PING_USERNAME: ${CTVL_PING_USERNAME}
      CTVL_PING_PASSWORD: ${CTVL_PING_PASSWORD}
    restart: unless-stopped
